FROM amd64/python:3.7-slim-buster



RUN unset EdgeModuleCACertificateFile
RUN unset EdgeHubConnectionString

WORKDIR /app

RUN pip install ptvsd==4.1.3
RUN pip install psycopg2-binary
RUN pip install ptvsd
RUN pip install --upgrade certifi
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .


CMD [ "python3", "-u", "./main.py" ]