FROM apache/nifi

USER root

EXPOSE 8080 8443 10000

RUN unset EdgeModuleCACertificateFile
RUN unset EdgeHubConnectionString

WORKDIR /module

COPY local.sh ./

WORKDIR ${NIFI_HOME}

########  ["./local.sh"]