FROM apache/nifi

USER root

EXPOSE 8080 8443 10000

RUN unset EdgeModuleCACertificateFile
RUN unset EdgeHubConnectionString

WORKDIR /module

COPY local.sh ./
COPY backup.sh ./

WORKDIR ${NIFI_HOME}

########   docker exec 09749260c619 /bin/sh -c "/module/local.sh"

ENTRYPOINT /module/local.sh