FROM grafana/grafana:latest
ENV GF_SECURITY_ADMIN_PASSWORD nb5PoBTg9B2iQ1OH4dMTii4fDVH2bIsVbOx4HA5U
#ENV GF_AUTH_LDAP_ENABLED=true
ENV GF_DATABASE_TYPE postgres
ENV GF_DATABASE_HOST timescaledb
ENV GF_DATABASE_NAME grafana
ENV GF_DATABASE_USER grafana
ENV GF_DATABASE_PASSWORD jw8s0F4
COPY ldap.toml /etc/grafana/
COPY custom.ini /etc/grafana/


RUN unset EdgeModuleCACertificateFile
RUN unset EdgeHubConnectionString